#!/usr/bin/env python3
"""Regenerate direct/level_alien_ship.gd from the DAME export in source/.

Reads com/tangentcode/sva/dame/Level_AlienShip.as (sprites, narration shapes,
object links) and the four mapCSV_AlienShip_*.csv tilemaps, and writes them as
GDScript constants so the Direct edition needs no runtime CSV import.
Run from this directory:  python3 dame_to_gd.py
"""
import csv, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
AS = open(os.path.join(HERE, "com/tangentcode/sva/dame/Level_AlienShip.as")).read()

def csv_rows(name):
    path = os.path.join(HERE, "assets", "mapCSV_AlienShip_%s.csv" % name)
    return [[int(v) for v in r] for r in csv.reader(open(path)) if r]

def section(fn):
    m = re.search(r"function %s\(.*?\{(.*?)\n\t\t\}" % fn, AS, re.S)
    return m.group(1)

out = ["extends RefCounted",
       "## GENERATED by source/dame_to_gd.py from Level_AlienShip.as + mapCSV_AlienShip_*.csv",
       "## (DAME export, Ludum Dare 21). Do not edit by hand.", ""]

# tilemaps: addTilemap(CSV, Img, x, y, tw, th, sx, sy, hits, collideIdx, drawIdx, ...)
tm = re.findall(r"layer(\w+) = addTilemap\( CSV_\w+, Img_\w+, ([-\d.]+), ([-\d.]+), (\d+), (\d+), ([\d.]+), ([\d.]+), \w+, (\d+), (\d+),", AS)
out.append("## [name, x, y, tile_w, tile_h, scroll_x, scroll_y, collide_idx, draw_idx], in masterLayer order")
out.append("const TILEMAPS := [")
for name, x, y, tw, th, sx, sy, ci, di in tm:
    out.append('\t["%s", %s, %s, %s, %s, %s, %s, %s, %s],' % (name, float(x), float(y), tw, th, float(sx), float(sy), ci, di))
out.append("]")
out.append("")
for name, *_ in tm:
    rows = csv_rows(name)
    out.append("const MAP_%s_W := %d" % (name.upper(), len(rows[0])))
    out.append("const MAP_%s := [" % name.upper())
    for r in rows:
        out.append("\t" + ",".join(str(v) for v in r) + ",")
    out.append("]")
    out.append("")

# narration: TextData(x, y, w, h, angle, "text", ...)
out.append("## TextData narration zones: [x, y, w, h, text]")
out.append("const NARRATION := [")
for x, y, w, h, t in re.findall(r'new TextData\(([-\d.]+), ([-\d.]+), ([\d.]+), ([\d.]+), [-\d.]+, "(.*?)","system"', section("addShapesForLayerNarration")):
    t = t.replace("\\r", "\n")
    out.append('\t[%s, %s, %s, %s, %s],' % (float(x), float(y), int(float(w)), int(float(h)), '"' + t.replace('"', '\\"').replace("\n", "\\n") + '"'))
out.append("]")
out.append("")

sprite_re = re.compile(r'(?:linkedObjectDictionary\[(\d+)\] = )?addSpriteToLayer\(null, (\w+), \w+ , ([-\d.]+), ([-\d.]+), ([-\d.]+), [\d.]+, [\d.]+, \w+, ([\d.]+), ([\d.]+), generateProperties\( (.*?) \), onAddCallback \);')
def props(s):
    d = {}
    for k, v in re.findall(r'name:"(\w+)", value:(\w+)', s):
        d[k] = v == "true"
    return d

for layer, fn in (("MOBILES", "addSpritesForLayerMobiles"), ("MACHINERY", "addSpritesForLayerMachinery")):
    out.append("## %s group: [class, x, y, link_id(-1), angle, scale_x, scale_y, props]" % layer.lower())
    out.append("const %s := [" % layer)
    for lid, cls, x, y, ang, sx, sy, p in sprite_re.findall(section(fn)):
        pr = props(p)
        prs = "{" + ", ".join('"%s": %s' % (k, "true" if v else "false") for k, v in pr.items()) + "}"
        out.append('\t["%s", %s, %s, %s, %s, %s, %s, %s],' % (cls, float(x), float(y), lid if lid else -1, float(ang), float(sx), float(sy), prs))
    out.append("]")
    out.append("")

out.append("## createLink(from, to) by linkedObjectDictionary id, in order")
out.append("const LINKS := [")
for a, b in re.findall(r"createLink\(linkedObjectDictionary\[(\d+)\], linkedObjectDictionary\[(\d+)\]", AS):
    out.append("\t[%s, %s]," % (a, b))
out.append("]")

open(os.path.join(HERE, "..", "direct", "level_alien_ship.gd"), "w").write("\n".join(out) + "\n")
print("wrote direct/level_alien_ship.gd")
