#!/usr/bin/env python3
"""Generate trail/trail_data.gd from source/lesson-code/*.txt.

Each lesson NN-name has two recovered files:
  NN-name.txt         code listings, split by "// ---- block N ----"
  NN-name.lesson.txt  the full lesson page text (prose + the same code)
Prose lines are those not present in the code listing; the prose that
precedes a block becomes that block's note.

Run from the repo root:  python3 games/brickslayer/source/gen_trail_data.py
"""
import json, re, pathlib

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "lesson-code"
OUT = HERE.parent / "trail" / "trail_data.gd"
BOILER = re.compile(r"^\d{4}/\d\d/\d\d .*alpha release")
BLOCK = re.compile(r"^// ---- block (\d+) ----$", re.M)


def gd(s: str) -> str:
    return json.dumps(s, ensure_ascii=True)


def parse_blocks(text):
    parts = BLOCK.split(text)
    blocks = []
    for i in range(1, len(parts), 2):
        blocks.append(parts[i + 1].strip("\n").rstrip())
    return blocks


def prose_lines(lesson_text, code_lines):
    out = []
    for raw in lesson_text.splitlines():
        s = raw.strip()
        if not s or BOILER.match(s):
            out.append(("blank", ""))
        elif s in code_lines:
            out.append(("code", s))
        else:
            out.append(("prose", s))
    return out


def tidy(lines):
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def build(slug):
    code_txt = SRC / f"{slug}.txt"
    lesson = (SRC / f"{slug}.lesson.txt").read_text(encoding="utf-8")
    blocks = parse_blocks(code_txt.read_text(encoding="utf-8")) if code_txt.exists() else []
    code_lines = {l.strip() for b in blocks for l in b.splitlines() if l.strip()}
    rows = prose_lines(lesson, code_lines)
    # first prose line is the page title
    title = ""
    for i, (k, s) in enumerate(rows):
        if k == "prose":
            title = s
            rows[i] = ("blank", "")
            break
    # block start markers: the first non-empty line of each block, searched in order
    starts = []
    pos = 0
    for b in blocks:
        first = next(l.strip() for l in b.splitlines() if l.strip())
        j = pos
        while j < len(rows) and not (rows[j][0] == "code" and rows[j][1] == first):
            j += 1
        if j >= len(rows):
            j = pos  # not found; attach no prose
        starts.append(j)
        pos = j + 1
    notes = []
    prev = 0
    for j in starts:
        notes.append(tidy([s for k, s in rows[prev:j] if k == "prose"] or []))
        # skip past this block's code rows
        prev = j
        while prev < len(rows) and rows[prev][0] != "prose":
            prev += 1
    outro = tidy([s for k, s in rows[prev:] if k == "prose"])
    if not blocks:
        outro = tidy([s for k, s in rows if k == "prose"])
    return {"slug": slug, "title": title, "blocks": blocks, "notes": notes, "outro": outro}


def main():
    slugs = sorted({p.name.split(".")[0] for p in SRC.glob("*.lesson.txt")})
    lessons = [build(s) for s in slugs]
    w = ["extends RefCounted",
         "## GENERATED by games/brickslayer/source/gen_trail_data.py — do not edit.",
         "## Brickslayer lesson trail recovered from javascriptgamer.com (2007).",
         "## Each lesson is a 'commit'; each code block is a step within it.",
         "",
         "const LESSONS := ["]
    for L in lessons:
        w.append("\t{")
        w.append(f"\t\t\"slug\": {gd(L['slug'])},")
        w.append(f"\t\t\"title\": {gd(L['title'])},")
        w.append(f"\t\t\"outro\": {gd(L['outro'])},")
        w.append("\t\t\"blocks\": [")
        for b in L["blocks"]:
            w.append(f"\t\t\t{gd(b)},")
        w.append("\t\t],")
        w.append("\t\t\"notes\": [")
        for n in L["notes"]:
            w.append(f"\t\t\t{gd(n)},")
        w.append("\t\t],")
        w.append("\t},")
    w.append("]")
    OUT.write_text("\n".join(w) + "\n", encoding="utf-8")
    for L in lessons:
        print(L["slug"], "|", L["title"], "|", len(L["blocks"]), "blocks")


if __name__ == "__main__":
    main()
