#!/usr/bin/env python3
"""One-shot decoder: giraffe.p8 __gfx__/__map__ → PNGs + map_data.gd.

Run from repo root or this directory:
  python3 games/giraffe/tools/extract_pico.py
"""
from __future__ import annotations

from pathlib import Path

# Pico-8 default 16-colour palette
PAL = [
    (0, 0, 0),
    (29, 43, 83),
    (126, 37, 83),
    (0, 135, 81),
    (171, 82, 54),
    (95, 87, 79),
    (194, 195, 199),
    (255, 241, 232),
    (255, 0, 77),
    (255, 163, 0),
    (255, 236, 39),
    (0, 228, 54),
    (41, 173, 255),
    (131, 118, 156),
    (255, 119, 168),
    (255, 204, 170),
]

ROOT = Path(__file__).resolve().parents[1]  # games/giraffe
CART = ROOT / "source" / "giraffe.p8"
OUT_ASSETS = ROOT / "direct" / "assets"
OUT_MAP = ROOT / "direct" / "map_data.gd"

# Sprites the cart draws: hero idle=1, walk=2/3, ground=16, bottom row=17
SPRITES = (1, 2, 3, 16, 17)


def parse_sections(text: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    cur: str | None = None
    buf: list[str] = []
    for line in text.splitlines():
        if line.startswith("__") and line.endswith("__"):
            if cur is not None:
                sections[cur] = buf
            cur = line.strip("_")
            buf = []
        elif cur is not None:
            buf.append(line)
    if cur is not None:
        sections[cur] = buf
    return sections


def build_sheet(gfx_rows: list[str]) -> list[list[int]]:
    """128×128 sheet; colour 0 is transparent when blitting sprites."""
    sheet = [[0] * 128 for _ in range(128)]
    for y, row in enumerate(gfx_rows):
        if y >= 128:
            break
        for x, ch in enumerate(row[:128]):
            sheet[y][x] = int(ch, 16)
    return sheet


def write_png(path: Path, pixels: list[list[int]], transparent0: bool = True) -> None:
    """Minimal RGBA PNG via stdlib only (no Pillow)."""
    import struct
    import zlib

    h = len(pixels)
    w = len(pixels[0]) if h else 0
    raw = bytearray()
    for row in pixels:
        raw.append(0)  # filter None
        for idx in row:
            r, g, b = PAL[idx & 15]
            a = 0 if (transparent0 and idx == 0) else 255
            raw.extend((r, g, b, a))
    compressed = zlib.compress(bytes(raw), 9)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(
            ">I", zlib.crc32(tag + data) & 0xFFFFFFFF
        )

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)  # 8-bit RGBA
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", compressed) + chunk(
        b"IEND", b""
    )
    path.write_bytes(png)


def sprite_pixels(sheet: list[list[int]], sid: int) -> list[list[int]]:
    sx = (sid % 16) * 8
    sy = (sid // 16) * 8
    return [sheet[sy + dy][sx : sx + 8] for dy in range(8)]


def parse_map(map_rows: list[str]) -> list[list[int]]:
    """Full Pico map width 128; pad to 32 rows (screen needs 16)."""
    rows: list[list[int]] = []
    for row in map_rows:
        cells = [int(row[i : i + 2], 16) for i in range(0, len(row), 2)]
        # pad/trim to 128
        if len(cells) < 128:
            cells.extend([0] * (128 - len(cells)))
        rows.append(cells[:128])
    while len(rows) < 32:
        rows.append([0] * 128)
    return rows[:32]


def write_map_gd(path: Path, rows: list[list[int]]) -> None:
    # Compact: only store the used 16×16 playfield (map(0,0) covers the screen).
    play = [r[:16] for r in rows[:16]]
    lines = [
        "extends RefCounted",
        "## Decoded Pico-8 __map__ for giraffe (16×16 screen cells from map 0,0).",
        "## Generated by tools/extract_pico.py — do not edit by hand.",
        "",
        "const W := 16",
        "const H := 16",
        "const CELL := 8",
        "",
        "## Row-major tile ids. Ground / platform = 16; bottom décor = 17.",
        "const TILES := [",
    ]
    for y, row in enumerate(play):
        body = ", ".join(str(t) for t in row)
        comma = "," if y < len(play) - 1 else ""
        lines.append(f"\t[{body}]{comma}  # y={y}")
    lines.append("]")
    lines.append("")
    lines.append("")
    lines.append("static func mget(mx: int, my: int) -> int:")
    lines.append("\tif mx < 0 or my < 0 or mx >= W or my >= H:")
    lines.append("\t\treturn 0")
    lines.append("\treturn TILES[my][mx]")
    lines.append("")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    sections = parse_sections(CART.read_text())
    if "gfx" not in sections or "map" not in sections:
        raise SystemExit("cart missing __gfx__ or __map__")
    sheet = build_sheet(sections["gfx"])
    OUT_ASSETS.mkdir(parents=True, exist_ok=True)

    # Full sheet (opaque bg for reference; sprites get transparent0 individually)
    write_png(OUT_ASSETS / "sheet.png", sheet, transparent0=False)

    for sid in SPRITES:
        write_png(OUT_ASSETS / f"spr_{sid}.png", sprite_pixels(sheet, sid), transparent0=True)

    rows = parse_map(sections["map"])
    write_map_gd(OUT_MAP, rows)
    print(f"wrote {OUT_ASSETS} sprites {list(SPRITES)} + sheet.png")
    print(f"wrote {OUT_MAP}")


if __name__ == "__main__":
    main()
