#!/usr/bin/env python3
"""Regenerate ../direct/level_pack.gd from levels/*.svg.

The GDScript twin of the original pack.py, which wrote code/LevelPack.hx so the
Flex-wrapped build (game1.swf) could embed every level instead of loading
levels/000N.svg over HTTP. Godot would import a loose .svg as a texture, so the
port embeds the raw XML the same way.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "direct", "level_pack.gd")

levels = sorted(f for f in os.listdir(os.path.join(HERE, "levels")) if f.endswith(".svg"))
lines = [
    "extends RefCounted",
    "## GENERATED by games/shep/source/gen_level_pack.py from source/levels/*.svg.",
    "## Do not edit by hand. Mirrors the original pack.py -> code/LevelPack.hx.",
    "",
    "const SVG := [",
]
for i, name in enumerate(levels):
    assert name == "%04d.svg" % i, name
    xml = open(os.path.join(HERE, "levels", name), encoding="utf-8").read().replace("\r\n", "\n")
    assert '"""' not in xml and "\\" not in xml
    lines.append('\t# %s' % name)
    lines.append('\t"""%s""",' % xml)
lines.append("]")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("wrote", os.path.relpath(OUT, HERE), len(levels), "levels")
