#!/usr/bin/env python3
"""Convert the GameMaker room XML into a GDScript const array.

Usage: python3 room_to_gd.py ../source/rooms/room0.room.gmx > ../direct/room0.gd
Every <instance> is kept in file order (duplicates included: the original
room really has stacked coins/walls, and each stacked coin scores).
"""
import re, sys

src = open(sys.argv[1]).read()
rows = []
for m in re.finditer(r'<instance objName="(\w+)" x="(-?[\d.]+)" y="(-?[\d.]+)"[^>]*'
                     r'scaleX="([^"]*)" scaleY="([^"]*)"', src):
    name, x, y, sx, sy = m.groups()
    rows.append('\t["%s", %s, %s, %s, %s],' % (name, x, y, float(sx), float(sy)))
w = re.search(r'<width>(\d+)</width>', src).group(1)
h = re.search(r'<height>(\d+)</height>', src).group(1)
sp = re.search(r'<speed>(\d+)</speed>', src).group(1)
print('extends RefCounted')
print('## GENERATED by games/toroidal_zombie_herder/tools/room_to_gd.py from')
print('## source/rooms/room0.room.gmx -- do not edit by hand.')
print()
print('const WIDTH := %s' % w)
print('const HEIGHT := %s' % h)
print('const SPEED := %s  ## room speed (steps per second)' % sp)
print()
print('## [object, x, y, scale_x, scale_y] in creation order.')
print('const INSTANCES := [')
print('\n'.join(rows))
print(']')
